version: "2"
services:
  db:
    image: mysql:latest
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
  web:
    build: .
    command: puma
    ports:
     - "9292:9292"
    links:
     - db
    volumes:
     - .:/inventory_manager
  sidekiq:
    build:
      context: ./sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml
    links:
     - redis
    volumes:
     - .:/inventory_manager
  redis:
    build:
      context: ./redis
    command: redis-server
    ports:
     - "6379:6379"
    volumes:
     - .:/inventory_manager