version: "2"
services:
  db:
    image: mysql:latest
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test 
  web:
    build: .
    command: puma
    ports:
     - "9292:9292"
    links:
     - db
    volumes:
     - .:/inventory_manager
