version: "2"
services:
  db:
    image: mysql:latest
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
  rails:
    build: .
    command: bundle install
    command: bundle exec rails s
    ports:
     - "3000:3000"
    links:
     - db
     - redis
    volumes:
     - /:/inner_fd
  sidekiq:
    build:
      context: ./sidekiq
    command: bash -c "bundle install && bundle exec sidekiq -C config/sidekiq.yml"
    links:
     - redis
    volumes:
     - /:/inner_fd
  redis:
    build:
      context: ./redis
    command: redis-server
    ports:
     - "6379:6379"
    volumes:
     - .:/inner_fd